# Generated by Django 5.0.6 on 2024-09-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0002_branch_product_remove_stockx_issued_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockx',
            name='stock_dealer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
