# Generated by Django 5.0.6 on 2024-09-01 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0004_stockx_issued_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockx',
            name='stock_time',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
    ]
