# Generated by Django 5.0.6 on 2024-09-02 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0006_stockx_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockx',
            name='issued_quantity',
        ),
    ]
