# Generated by Django 5.0.6 on 2024-09-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0007_remove_stockx_issued_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
