# Generated by Django 5.0.6 on 2024-09-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0008_alter_branch_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_type', models.CharField(max_length=255)),
                ('total_quantity', models.PositiveIntegerField()),
                ('image', models.TextField()),
            ],
        ),
    ]
