# Generated by Django 5.0.6 on 2024-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0011_stockx_issued_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
