# Generated by Django 5.0.6 on 2024-09-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0012_sale_date_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
