# Generated by Django 5.0.6 on 2024-09-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0013_alter_produce_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='receipt_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
