# Generated by Django 5.0.6 on 2024-09-09 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0014_sale_receipt_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='modality',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=6),
        ),
    ]
