# Generated by Django 5.0.6 on 2024-09-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Grocery_app', '0015_sale_modality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='modality',
        ),
        migrations.AlterField(
            model_name='sale',
            name='amount_received',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
